//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelevantCodes.ExtentReports.View.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelevantCodes.ExtentReports.View.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories_heading {
            get {
                return ResourceManager.GetString("categories_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunDate.
        /// </summary>
        public static string categories_th_runDate {
            get {
                return ResourceManager.GetString("categories_th_runDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string categories_th_status {
            get {
                return ResourceManager.GetString("categories_th_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestName.
        /// </summary>
        public static string categories_th_testName {
            get {
                return ResourceManager.GetString("categories_th_testName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to others.
        /// </summary>
        public static string dashboard_panel_label_others {
            get {
                return ResourceManager.GetString("dashboard_panel_label_others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step(s) failed.
        /// </summary>
        public static string dashboard_panel_label_stepsFailed {
            get {
                return ResourceManager.GetString("dashboard_panel_label_stepsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step(s) passed.
        /// </summary>
        public static string dashboard_panel_label_stepsPassed {
            get {
                return ResourceManager.GetString("dashboard_panel_label_stepsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test(s) failed.
        /// </summary>
        public static string dashboard_panel_label_testsFailed {
            get {
                return ResourceManager.GetString("dashboard_panel_label_testsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test(s) passed.
        /// </summary>
        public static string dashboard_panel_label_testsPassed {
            get {
                return ResourceManager.GetString("dashboard_panel_label_testsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string dashboard_panel_name_categories {
            get {
                return ResourceManager.GetString("dashboard_panel_name_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string dashboard_panel_name_end {
            get {
                return ResourceManager.GetString("dashboard_panel_name_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string dashboard_panel_name_environment {
            get {
                return ResourceManager.GetString("dashboard_panel_name_environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Percentage.
        /// </summary>
        public static string dashboard_panel_name_passPercentage {
            get {
                return ResourceManager.GetString("dashboard_panel_name_passPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string dashboard_panel_name_start {
            get {
                return ResourceManager.GetString("dashboard_panel_name_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsView.
        /// </summary>
        public static string dashboard_panel_name_stepsView {
            get {
                return ResourceManager.GetString("dashboard_panel_name_stepsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests View.
        /// </summary>
        public static string dashboard_panel_name_testsView {
            get {
                return ResourceManager.GetString("dashboard_panel_name_testsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSteps.
        /// </summary>
        public static string dashboard_panel_name_totalSteps {
            get {
                return ResourceManager.GetString("dashboard_panel_name_totalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tests.
        /// </summary>
        public static string dashboard_panel_name_totalTests {
            get {
                return ResourceManager.GetString("dashboard_panel_name_totalTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Taken.
        /// </summary>
        public static string dashboard_panel_name_totalTimeTaken {
            get {
                return ResourceManager.GetString("dashboard_panel_name_totalTimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string dashboard_panel_th_name {
            get {
                return ResourceManager.GetString("dashboard_panel_th_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param.
        /// </summary>
        public static string dashboard_panel_th_param {
            get {
                return ResourceManager.GetString("dashboard_panel_th_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string dashboard_panel_th_value {
            get {
                return ResourceManager.GetString("dashboard_panel_th_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyrights licensed under the New BSD License.
        /// </summary>
        public static string head_copyrights {
            get {
                return ResourceManager.GetString("head_copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string head_documentation {
            get {
                return ResourceManager.GetString("head_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string head_library {
            get {
                return ResourceManager.GetString("head_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtentReports (by Anshoo Arora) is a reporting library for automation testing for .NET and Java. It creates detailed and beautiful HTML reports for modern browsers. ExtentReports shows test and step summary along with dashboards, system and environment details for quick analysis of your tests..
        /// </summary>
        public static string head_metaDescription {
            get {
                return ResourceManager.GetString("head_metaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestRunner Logs.
        /// </summary>
        public static string logs_heading {
            get {
                return ResourceManager.GetString("logs_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string modal_button_save {
            get {
                return ResourceManager.GetString("modal_button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string modal_heading_selectStatus {
            get {
                return ResourceManager.GetString("modal_heading_selectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Tests Count Setting.
        /// </summary>
        public static string modal_heading_testCount {
            get {
                return ResourceManager.GetString("modal_heading_testCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Tests Only.
        /// </summary>
        public static string modal_selection_childTests {
            get {
                return ResourceManager.GetString("modal_selection_childTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Tests Only (Does not include child nodes in counts).
        /// </summary>
        public static string modal_selection_parentTestOnly {
            get {
                return ResourceManager.GetString("modal_selection_parentTestOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Tests Without Child Tests + Child Tests.
        /// </summary>
        public static string modal_selection_parentWithoutChildNodes {
            get {
                return ResourceManager.GetString("modal_selection_parentWithoutChildNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string nav_menu_analysis {
            get {
                return ResourceManager.GetString("nav_menu_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string nav_menu_categories {
            get {
                return ResourceManager.GetString("nav_menu_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Details.
        /// </summary>
        public static string nav_menu_testDetails {
            get {
                return ResourceManager.GetString("nav_menu_testDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestRunner Logs.
        /// </summary>
        public static string nav_menu_testRunnerLogs {
            get {
                return ResourceManager.GetString("nav_menu_testRunnerLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle dark theme. To enable by default, use js configuration $(&apos;body&apos;).addClass(&apos;dark&apos;);.
        /// </summary>
        public static string nav_menuright_themeSelectorMessage {
            get {
                return ResourceManager.GetString("nav_menuright_themeSelectorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string status_fail {
            get {
                return ResourceManager.GetString("status_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string status_info {
            get {
                return ResourceManager.GetString("status_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string status_pass {
            get {
                return ResourceManager.GetString("status_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string status_skip {
            get {
                return ResourceManager.GetString("status_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string status_unknown {
            get {
                return ResourceManager.GetString("status_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string status_warning {
            get {
                return ResourceManager.GetString("status_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string tests_filters_clearFilters {
            get {
                return ResourceManager.GetString("tests_filters_clearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dashboard.
        /// </summary>
        public static string tests_filters_enableDashboard {
            get {
                return ResourceManager.GetString("tests_filters_enableDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Charts on Filters.
        /// </summary>
        public static string tests_filters_refreshCharts {
            get {
                return ResourceManager.GetString("tests_filters_refreshCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tests.
        /// </summary>
        public static string tests_filters_searchTests {
            get {
                return ResourceManager.GetString("tests_filters_searchTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test ended time.
        /// </summary>
        public static string tests_test_info_testEndTime {
            get {
                return ResourceManager.GetString("tests_test_info_testEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test started time.
        /// </summary>
        public static string tests_test_info_testStartTime {
            get {
                return ResourceManager.GetString("tests_test_info_testStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time taken to finish.
        /// </summary>
        public static string tests_test_info_timeTaken {
            get {
                return ResourceManager.GetString("tests_test_info_timeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string tests_test_log_th_details {
            get {
                return ResourceManager.GetString("tests_test_log_th_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string tests_test_log_th_status {
            get {
                return ResourceManager.GetString("tests_test_log_th_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string tests_test_log_th_timestamp {
            get {
                return ResourceManager.GetString("tests_test_log_th_timestamp", resourceCulture);
            }
        }
    }
}
